- id: '1589211936901'
  alias: Watching TV
  description: ''
  trigger:
  - entity_id: media_player.living_room_tv
    from: idle
    platform: state
    to: playing
  condition: []
  action:
  - condition: state
    entity_id: input_boolean.television
    state: '''on'''
- id: '1589212835864'
  alias: Turn on lights at sunset
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - scene: scene.evening
- id: '1589214058856'
  alias: Pause TV
  description: ''
  trigger:
  - entity_id: media_player.living_room_tv
    from: playing
    platform: state
    to: idle
  condition: []
  action:
  - condition: state
    entity_id: input_boolean.television
    state: '''off'''
- id: '1589822448722'
  alias: Graeme computer light
  description: ''
  trigger:
  - entity_id: device_tracker.36_e6_85_88_24_fb
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: person.graeme
    state: home
  action:
  - scene: scene.graeme_work
- id: '1589823128922'
  alias: Carol computer light
  description: ''
  trigger:
  - entity_id: device_tracker.mbp13c0inamotta
    from: not_home
    platform: state
    to: home
  - entity_id: device_tracker.mbp_de_ana_66
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: person.carol
    state: home
  action:
  - scene: scene.carol_work
- id: '1590765489158'
  alias: Open Blinds Mon-Fri
  description: ''
  trigger:
  - at: '20:59:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data: {}
    service: script.wake_up
- id: '1590765489157'
  alias: Open Blinds Sat-Sun
  description: ''
  trigger:
  - at: 08:00:00
    platform: time
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - data: {}
    service: script.wake_up
- id: '1591640831293'
  alias: Wake Up 2
  description: ''
  trigger:
  - device_id: a70875db160c49319a6cb6f92bb81119
    domain: binary_sensor
    entity_id: binary_sensor.living_room_pir_2
    platform: device
    type: motion
  condition:
  - condition: state
    entity_id: input_boolean.blinds_primed
    state: 'on'
  action:
  - data: {}
    service: script.Wake_up_2
- id: '1591645794362'
  alias: Cristo light motion
  description: ''
  trigger:
  - device_id: a70875db160c49319a6cb6f92bb81119
    domain: binary_sensor
    entity_id: binary_sensor.living_room_pir_2
    platform: device
    type: motion
  condition:
  - condition: device
    device_id: f09cf8edf8944505a265dd63eafc7ba6
    domain: light
    entity_id: light.graeme_s_lamp
    type: is_off
  - condition: device
    device_id: 8e00d81156f2483280581309593be0e7
    domain: light
    entity_id: light.carol_s_lamp
    type: is_off
  - condition: device
    device_id: f253075c95a048228183a8f3495349e1
    domain: media_player
    entity_id: media_player.living_room_tv
    type: is_off
  - condition: or
    conditions:
    - after: sunset
      before: sunrise
      condition: sun
    - condition: state
      entity_id: cover.sonoff_1000d67323
      state: closed
  action:
  - device_id: 6aed5e2038814e7cbf5f43ec238a4691
    domain: switch
    entity_id: switch.cristo_light
    type: turn_on
  - delay: '[object Object]'
  - device_id: 6aed5e2038814e7cbf5f43ec238a4691
    domain: switch
    entity_id: switch.cristo_light
    type: turn_off
