- id: '1589211936901'
  alias: Watching TV
  description: ''
  trigger:
  - entity_id: media_player.living_room_tv
    from: idle
    platform: state
    to: playing
  condition: []
  action:
  - condition: state
    entity_id: input_boolean.television
    state: '''on'''
- id: '1589212835864'
  alias: Turn on lights at sunset
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - scene: scene.evening
- id: '1589214058856'
  alias: Pause TV
  description: ''
  trigger:
  - entity_id: media_player.living_room_tv
    from: playing
    platform: state
    to: idle
  condition: []
  action:
  - condition: state
    entity_id: input_boolean.television
    state: '''off'''
- id: '1589822448722'
  alias: Graeme computer light
  description: ''
  trigger:
  - entity_id: device_tracker.36_e6_85_88_24_fb
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: person.graeme
    state: home
  action:
  - scene: scene.graeme_work
- id: '1589823128922'
  alias: Carol computer light
  description: ''
  trigger:
  - entity_id: device_tracker.mbp13c0inamotta
    from: not_home
    platform: state
    to: home
  - entity_id: device_tracker.mbp_de_ana_66
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: person.carol
    state: home
  action:
  - scene: scene.carol_work
- id: '1590765489156'
  alias: Open Blinds Mon-Fri
  description: ''
  trigger:
  - at: 07:00:00
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data: {}
    service: script.open_blinds
- id: '1590765489157'
  alias: Open Blinds Sat-Sun
  description: ''
  trigger:
  - at: 08:00:00
    platform: time
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - data: {}
    service: script.open_blinds
