
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: death-star.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
device_tracker:
  - platform: huawei_router
    host: 192.168.1.1
    username: vodafone
    password: !secret router
  - platform: bluetooth_tracker
  - platform: bluetooth_le_tracker
lovelace:
  mode: yaml

google_assistant:
  project_id: home-assistant-277315
  service_account: !include Home Assistant-b640ced71d95.json
  report_state: true
  exposed_domains:
    - switch
    - light

sonoff:
  username: graemejallen83@gmail.com
  password: !secret sonoff
  scan_interval: 60 #(optional, lower values than 60 won't work anymore!)
  grace_period: 600 #(optional)
  api_region: 'eu' #(optional)
  entity_prefix: True #(optional)
  debug: false #(optional)
  
####################################################################################### 
## Templates (Used for updating text in the UI and converting sensors to CSS values )
#######################################################################################  
sensor:

  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
      
  - platform: template
    sensors:  
      ## Converts time and date into sentence for UI     
      day:
        entity_id: sensor.date
        value_template: >
          {% set days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] %}
          {{ days[now().weekday()] }}
      month:
        value_template: >
          {% set months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"] %}
          {{ strptime(states('sensor.date'), '%Y-%m-%d').day }}
          {{ months[now().month-1] }} 
          
      date_string:
        friendly_name: "Full Date"
        value_template: "{{ states('sensor.day') }}, {{ states('sensor.month') }} {{ now().year }}"  
        
      ambient_light_calc:
        friendly_name: 'Calculated Ambient Light'
        value_template: '{{ ((30 + states.sun.sun.attributes.elevation | float ) * (1 - ((states.sensor.weather_low_clouds.state | float / 100) + (states.sensor.weather_medium_clouds.state | float / 150) + (states.sensor.weather_high_clouds.state | float / 200)))) |float|round(1) }}'

## Weather

  - platform: yr

  - platform: yr
    name: Weather
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature


weather:
  - platform: 'buienradar'
    name: Weather-old
    latitude: 41.182192
    longitude: -8.625669
    forecast: true

binary_sensor:
  - platform: workday
    country: PT   

  - platform: tod
    name: Night
    after: sunset
    before: sunrise    

input_number:
  nightime:
    name: Nightime value
    initial: 0
    min: 0
    max: 1
    step: 1
    mode: box
    
  range_high:
    name: High Limit
    initial: 8.0
    min: 0
    max: 30
    
  range_low:
    name: High Limit
    initial: 4.0
    min: 0
    max: 30
####################################################################################### 
## DUMMY DEVICES
#######################################################################################
  daylight_tester:
    name: brightness
    initial: 100
    min: 0
    max: 100
    step: 1
    

    

