esphome:
  name: sensor_node1
  platform: ESP8266
  board: esp01_1m
  includes:
    - tsl2591.h

  libraries:
    - "Adafruit TSL2591 Library"

wifi:
  ssid: "The Force"
  password: "Obi-Wan&Luke"
  fast_connect: True
  power_save_mode: high

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sensor Node1 Fallback Hotspot"
    password: "bBtGW2pPk0gy"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: dht
    pin: GPIO14
    model: dht22
    temperature:
      name: "Outside Temperature"
    humidity:
      name: "Outside Humidity"
    update_interval: 30s
    
  - platform: custom
    lambda: |-
      auto my_sensor = new Tsl2591();
      App.register_component(my_sensor);
      return {my_sensor};
    
    sensors:
      name: "Lux" 
      unit_of_measurement: lux
      filters:
     # - filter_out: 0
      - filter_out: 65535
      
  - platform: homeassistant
    name: "Outdoor wake duration"
    id: outdoor_wake_duration
    entity_id: sensor.outdoor_wake_duration      
      
  - platform: homeassistant
    name: "Outdoor sleep duration"
    id: outdoor_sleep_duration
    entity_id: sensor.outdoor_sleep_duration
    on_value:
      then:
      - lambda:  'id(start_deep_sleep).set_sleep_duration(id(outdoor_sleep_duration).state * 60000);'
      - delay: !lambda 'return id(outdoor_wake_duration).state * 1000;'
      - deep_sleep.enter: start_deep_sleep      
      
i2c:
  sda: GPIO4
  scl: GPIO0    
  scan: false

deep_sleep:  
  id: start_deep_sleep
#  run_duration: 30s
#  sleep_duration: 15min
    

