esphome:
  name: sensor_node2
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "The Force"
  password: "Obi-Wan&Luke"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sensor Node2 Fallback Hotspot"
    password: "0X93H0KPKMTD"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: dht
    pin: GPIO16
    model: dht22
    temperature:
      name: "Inside Temperature"
      filters:
      - lambda: return x - 2.5;
    humidity:
      name: "Inside Humidity"
      filters:
      - lambda: return x + 6;
    update_interval: 30s
    
binary_sensor:
  - platform: gpio
    pin: GPIO5
    name: "Living Room PIR"
    device_class: motion    


      
light:
  - platform: rgb
    name: "RGB LED"
    id: rgb_led
    red: output_red
    green: output_green
    blue: output_blue
output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO13
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14


switch:
  - platform: restart
    name: "Restart"
    id: restart_switch